export const ITEM_DEFINITIONS = {
    pillar_shard_amber: {
        id: 'pillar_shard_amber',
        name: 'Amber Pillar-Shard',
        category: 'pillar-shard',
        icon: 'assets/items/pillar_shard_amber.png',
        canon: 'Amberwake Desert Pillar',
    },
    pillar_shard_rust: {
        id: 'pillar_shard_rust',
        name: 'Rust Pillar-Shard',
        category: 'pillar-shard',
        icon: 'assets/items/pillar_shard_rust.png',
        canon: 'Rust-Rock Canyon Pillar',
    },
    pillar_shard_salt: {
        id: 'pillar_shard_salt',
        name: 'Salt Pillar-Shard',
        category: 'pillar-shard',
        icon: 'assets/items/pillar_shard_salt.png',
        canon: 'Shimmering Salt Flats Pillar',
    },
    pillar_shard_tide: {
        id: 'pillar_shard_tide',
        name: 'Tide Pillar-Shard',
        category: 'pillar-shard',
        icon: 'assets/items/pillar_shard_tide.png',
        canon: 'Sunken Tropics Pillar',
    },
    pillar_shard_cinder: {
        id: 'pillar_shard_cinder',
        name: 'Cinder Pillar-Shard',
        category: 'pillar-shard',
        icon: 'assets/items/pillar_shard_cinder.png',
        canon: 'Burnt Plains Pillar',
    },
    pillar_shard_dust: {
        id: 'pillar_shard_dust',
        name: 'Dust Pillar-Shard',
        category: 'pillar-shard',
        icon: 'assets/items/pillar_shard_dust.png',
        canon: 'Duststeppe Wilds Pillar',
    },
    wormp_trophy_blightworm: {
        id: 'wormp_trophy_blightworm',
        name: 'Blightworm Trophy',
        category: 'wormp-trophy',
        icon: 'assets/items/wormp_trophy_blightworm.png',
        canon: 'Blightworm Wormp',
    },
    wormp_trophy_sunscarab: {
        id: 'wormp_trophy_sunscarab',
        name: 'Sunscarab Trophy',
        category: 'wormp-trophy',
        icon: 'assets/items/wormp_trophy_sunscarab.png',
        canon: 'Sunscarab Wormp',
    },
    wormp_trophy_dune_warden: {
        id: 'wormp_trophy_dune_warden',
        name: 'Dune Warden Trophy',
        category: 'wormp-trophy',
        icon: 'assets/items/wormp_trophy_dune_warden.png',
        canon: 'Dune Warden Wormp',
    },
    wormp_trophy_rusher: {
        id: 'wormp_trophy_rusher',
        name: 'Rusher Trophy',
        category: 'wormp-trophy',
        icon: 'assets/items/wormp_trophy_rusher.png',
        canon: 'Canyon Rusher Wormp',
    },
    wormp_trophy_tactical_archer: {
        id: 'wormp_trophy_tactical_archer',
        name: 'Archer Trophy',
        category: 'wormp-trophy',
        icon: 'assets/items/wormp_trophy_tactical_archer.png',
        canon: 'Salt Picket Wormp',
    },
    wormp_trophy_goliath: {
        id: 'wormp_trophy_goliath',
        name: 'Goliath Trophy',
        category: 'wormp-trophy',
        icon: 'assets/items/wormp_trophy_goliath.png',
        canon: 'Goliath Chakram Wormp',
    },
    wormp_trophy_world_coil: {
        id: 'wormp_trophy_world_coil',
        name: 'World-Coil Trophy',
        category: 'wormp-trophy',
        icon: 'assets/items/wormp_trophy_world_coil.png',
        canon: 'Sand Worm / World-Coil Wormp',
    },
    master_relic_might: {
        id: 'master_relic_might',
        name: 'Master Relic of Might',
        category: 'master-relic',
        icon: 'assets/items/master_relic_might.png',
        canon: 'Four Masters relic set',
    },
    master_relic_swift: {
        id: 'master_relic_swift',
        name: 'Master Relic of Swiftness',
        category: 'master-relic',
        icon: 'assets/items/master_relic_swift.png',
        canon: 'Four Masters relic set',
    },
    master_relic_ward: {
        id: 'master_relic_ward',
        name: 'Master Relic of Ward',
        category: 'master-relic',
        icon: 'assets/items/master_relic_ward.png',
        canon: 'Four Masters relic set',
    },
    master_relic_memory: {
        id: 'master_relic_memory',
        name: 'Master Relic of Memory',
        category: 'master-relic',
        icon: 'assets/items/master_relic_memory.png',
        canon: 'Sunken Relic / Mnemoforge memory magic',
    },
    banner_mark_ash: {
        id: 'banner_mark_ash',
        name: 'Ash Banner-Mark',
        category: 'banner-mark',
        icon: 'assets/items/banner_mark_ash.png',
        canon: 'Banner Three',
    },
    banner_mark_tide: {
        id: 'banner_mark_tide',
        name: 'Tide Banner-Mark',
        category: 'banner-mark',
        icon: 'assets/items/banner_mark_tide.png',
        canon: 'Banner Three',
    },
    banner_mark_star: {
        id: 'banner_mark_star',
        name: 'Star Banner-Mark',
        category: 'banner-mark',
        icon: 'assets/items/banner_mark_star.png',
        canon: 'Banner Three',
    },
    shardwing_talon: {
        id: 'shardwing_talon',
        name: 'Shardwing Talon',
        category: 'shardwing-remnant',
        icon: 'assets/items/shardwing_talon.png',
        canon: 'Shardwing Wyvern remnant',
    },
    shardwing_scale: {
        id: 'shardwing_scale',
        name: 'Shardwing Scale',
        category: 'shardwing-remnant',
        icon: 'assets/items/shardwing_scale.png',
        canon: 'Shardwing Wyvern remnant',
    },
    shardwing_eye: {
        id: 'shardwing_eye',
        name: 'Shardwing Eye',
        category: 'shardwing-remnant',
        icon: 'assets/items/shardwing_eye.png',
        canon: 'Shardwing Wyvern remnant',
    },
    shardwing_pinion: {
        id: 'shardwing_pinion',
        name: 'Shardwing Pinion',
        category: 'shardwing-remnant',
        icon: 'assets/items/shardwing_pinion.png',
        canon: 'Shardwing Wyvern remnant',
    },
    aether_font_vial: {
        id: 'aether_font_vial',
        name: 'Aether Font Vial',
        category: 'consumable',
        icon: 'assets/items/aether_font_vial.png',
        canon: 'Aether Font surge',
    },
    herbal_draught: {
        id: 'herbal_draught',
        name: 'Herbal Draught',
        category: 'consumable',
        icon: 'assets/items/herbal_draught.png',
        canon: 'Ila / Mira healing rewards',
    },
    tide_thread: {
        id: 'tide_thread',
        name: 'Tide Thread',
        category: 'consumable',
        icon: 'assets/items/tide_thread.png',
        canon: 'Tide Medic wound magic',
    },
    salt_glass_vial: {
        id: 'salt_glass_vial',
        name: 'Salt Glass Vial',
        category: 'consumable',
        icon: 'assets/items/salt_glass_vial.png',
        canon: 'Qira Salt Glasswright',
    },
    cinder_ash: {
        id: 'cinder_ash',
        name: 'Cinder Ash',
        category: 'consumable',
        icon: 'assets/items/cinder_ash.png',
        canon: 'Burnt Plains ash-road',
    },
    shardfang_dagger: {
        id: 'shardfang_dagger',
        name: 'Shardfang Dagger',
        category: 'equipment',
        icon: 'assets/items/shardfang_dagger.png',
        canon: 'Shardwing talon starter weapon',
    },
    driftstep_boots: {
        id: 'driftstep_boots',
        name: 'Driftstep Boots',
        category: 'equipment',
        icon: 'assets/items/driftstep_boots.png',
        canon: 'Player dash / Wayfinder step',
    },
    lantern_ward_charm: {
        id: 'lantern_ward_charm',
        name: 'Lantern Ward Charm',
        category: 'equipment',
        icon: 'assets/items/lantern_ward_charm.png',
        canon: 'Drift Lantern and ward buffs',
    },
    elaras_map: {
        id: 'elaras_map',
        name: "Elara's Map",
        category: 'equipment',
        icon: 'assets/items/elaras_map.png',
        canon: 'Elara map unlock',
    },
    rowboat_oar_token: {
        id: 'rowboat_oar_token',
        name: 'Rowboat Oar Token',
        category: 'equipment',
        icon: 'assets/items/rowboat_oar_token.png',
        canon: 'Boatman / rowboat unlock',
    },
    mnemoforge_compass: {
        id: 'mnemoforge_compass',
        name: 'Mnemoforge Compass',
        category: 'equipment',
        icon: 'assets/items/mnemoforge_compass.png',
        canon: 'Mnemoforge respec altar',
    },
};
